#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 0.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

install:

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:

build_script:
  - ps: ./scripts/create_release.ps1

after_build:

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: tshock_cn_release.zip