language: csharp
solution: "./TShockAPI/TShockAPI.csproj"
sudo: false
install:
- nuget restore
script: python ./scripts/create_release.py
notifications:
  slack:
    secure: O4Nibe2fdaUa2ZxuETUg6WEoQKvNM2CotnfaIVgm3fjfe61dfE1P+EgTpbwDG8646jSmpTqMDw8Z6I/WJwGTlXV/ZQsbwu63Cps4MgOTvPHZ0Lsye5azySlJZs1iI4ItYSj2czXfcnJ+qAl1SOOkXJrjB5uyTMWtDpCrSCFB3MA=
before_install:
- openssl aes-256-cbc -K $encrypted_1d7cd15ffdb4_key -iv $encrypted_1d7cd15ffdb4_iv
  -in ./scripts/ssh_private_key.enc -out ./scripts/ssh_private_key -d
